# m09 — Infrastructure as Code (Terraform) for the churn platform, fully LOCAL.
#
# No cloud account and no credentials. We use only offline providers:
#   - hashicorp/random  -> random identifiers/suffixes,
#   - hashicorp/local   -> real files and directories on disk,
#   - hashicorp/null    -> null_resource + local-exec as a "provisioning step".
#
# Local files/directories REPRESENT the churn ML platform:
#   a bucket for model artifacts, model registry configuration, environment configs
#   (dev/stage). Everything lands under infra/build/.

terraform {
  required_version = ">= 1.5.0"

  required_providers {
    local = {
      source  = "hashicorp/local"
      version = ">= 2.5"
    }
    random = {
      source  = "hashicorp/random"
      version = ">= 3.6"
    }
    null = {
      source  = "hashicorp/null"
      version = ">= 3.2"
    }
  }

  # State is kept LOCALLY (terraform.tfstate in this directory) — default backend.
}

provider "random" {}
provider "local" {}
provider "null" {}

# --- Random identifiers -----------------------------------------------------

resource "random_pet" "suffix" {
  length    = 2
  separator = "-"
}

resource "random_id" "platform" {
  byte_length = 4
}

locals {
  output_root   = abspath(var.output_root)
  platform_id   = random_id.platform.hex
  name_suffix   = random_pet.suffix.id
  platform_full = "${var.platform_name}-${local.platform_id}"
}

# --- Main churn platform manifest (local_file) -----------------------------

resource "local_file" "platform_manifest" {
  filename = "${local.output_root}/platform.json"
  content = jsonencode({
    platform       = local.platform_full
    primary_env    = var.environment
    owner          = var.owner
    model_name     = var.model_name
    suffix         = local.name_suffix
    environments   = var.environments
    artifact_root  = local.output_root
    managed_by     = "terraform"
    generated_note = "File generated by Terraform — do not edit manually."
  })
}

# --- Environments via a REUSABLE module ------------------------------------

module "ml_env" {
  source   = "./modules/ml_environment"
  for_each = toset(var.environments)

  environment   = each.value
  platform_name = var.platform_name
  model_name    = var.model_name
  suffix        = local.name_suffix
  root_dir      = local.output_root
}

# --- Provisioning step (null_resource + local-exec) ------------------------

resource "null_resource" "provision_notice" {
  triggers = {
    platform     = local.platform_full
    environments = join(",", var.environments)
    manifest     = local_file.platform_manifest.content
  }

  provisioner "local-exec" {
    command = "echo '[provision] Churn platform ${local.platform_full} ready; environments: ${join(", ", var.environments)}; artifacts in ${local.output_root}'"
  }

  depends_on = [
    local_file.platform_manifest,
    module.ml_env,
  ]
}
